name: Release

permissions:
  contents: write

on:
  release:
    types: [released]

jobs:
  release-binaries:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/free-disk-space
      - uses: ./.github/actions/ubuntu-dependencies

      - name: Build node and runtime (release)
        run: cargo build --locked --release
        timeout-minutes: 90

      - name: Upload the binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/solochain-template-node
            target/release/wbuild/solochain-template-runtime/solochain_template_runtime.compact.compressed.wasm
